src/Entity/Stuff.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StuffRepository")
 */
class Stuff
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="stuffs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id = null): self
    {
        $this->user_id = $user_id;

        return $this;
    }
}

src/Form/StuffType.php
<?php

namespace App\Form;

use App\Entity\Stuff;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StuffType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('url')
            ->add('created_at')
            ->add('updated_at')
            ->add('user_id', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'username',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Stuff::class,
        ]);
    }
}

src/Controller/StuffController.php
<?php

namespace App\Controller;

use App\Entity\Stuff;
use App\Entity\User;
use App\Form\StuffType;
use App\Repository\StuffRepository;
use App\Service\StuffService;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/stuff")
 * @IsGranted("ROLE_USER")
 * @method User getUser()
 */
class StuffController extends AbstractController
{
    /**
     * @Route("/", name="stuff_index", methods={"GET"})
     * @param StuffRepository $stuffRepository
     * @return Response
     */
    public function index(StuffRepository $stuffRepository, StuffService $stuffService): Response
    {
        return $this->render('stuff/index.html.twig', [
            'stuffs' => $stuffRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="stuff_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $stuff = new Stuff();
        $stuff->setUserId($this->getUser());
        $form = $this->createForm(StuffType::class, $stuff);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($stuff);
            $entityManager->flush();

            return $this->redirectToRoute('stuff_index');
        }

        return $this->render('stuff/new.html.twig', [
            'stuff' => $stuff,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="stuff_show", methods={"GET"})
     */
    public function show(Stuff $stuff): Response
    {
        return $this->render('stuff/show.html.twig', [
            'stuff' => $stuff,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="stuff_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Stuff $stuff): Response
    {
        $stuff->setUserId($this->getUser());
        $form = $this->createForm(StuffType::class, $stuff);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('stuff_index');
        }

        return $this->render('stuff/edit.html.twig', [
            'stuff' => $stuff,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="stuff_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Stuff $stuff): Response
    {
        if ($this->isCsrfTokenValid('delete' . $stuff->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($stuff);
            $entityManager->flush();
        }

        return $this->redirectToRoute('stuff_index');
    }
}

templates/stuff/_delete_form.html.twig
<form method="post" action="{{ path('stuff_delete', {'id': stuff.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ stuff.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/stuff/_form.html.twig
{{ form_start(form) }}
<div class="row">
    <div class="col-sm-6">{{ form_row(form.title) }}</div>
    <div class="col-sm-6">{{ form_row(form.url) }}</div>
</div>
<div class="row">
    <div class="col-sm-6">{{ form_row(form.created_at) }}</div>
    <div class="col-sm-6">{{ form_row(form.updated_at) }}</div>
</div>
<div class="row">
    <div class="col-sm-6">{{ form_row(form.user_id) }}</div>

</div>

<div class="col-sm-3">
    <button id="save" class="btn btn-success">{{ button_label|default('Save') }}</button>
</div>
{#{{ form_widget(form) }}#}
{{ form_end(form) }}

templates/stuff/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Stuff{% endblock %}

{% block body %}
    <h1>Edit Stuff</h1>
    {{ include('stuff/_form.html.twig', {'button_label': 'Update'}) }}

    <div class="col-sm-3">
        <a class="btn btn-primary" href="{{ path('stuff_index') }}">back to list</a>
    </div>

    <div class="col-sm-3">
        {{ include('stuff/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/stuff/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Stuff index{% endblock %}

{% block body %}
    <h1>Stuff index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Url</th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for stuff in stuffs %}
            <tr>
                <td>{{ stuff.id }}</td>
                <td>{{ stuff.title }}</td>
                <td>{{ stuff.url }}</td>
                <td>{{ stuff.createdAt ? stuff.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ stuff.updatedAt ? stuff.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('stuff_show', {'id': stuff.id}) }}">show</a>
                    <a href="{{ path('stuff_edit', {'id': stuff.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('stuff_new') }}">Create new</a>
{% endblock %}

templates/stuff/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Stuff{% endblock %}

{% block body %}
    <h1>Create new Stuff</h1>

    {{ include('stuff/_form.html.twig') }}

    <a href="{{ path('stuff_index') }}">back to list</a>
{% endblock %}

templates/stuff/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Stuff{% endblock %}

{% block body %}
    <h1>Stuff</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ stuff.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ stuff.title }}</td>
            </tr>
            <tr>
                <th>Url</th>
                <td>{{ stuff.url }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ stuff.createdAt ? stuff.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ stuff.updatedAt ? stuff.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('stuff_index') }}">back to list</a>

    <a href="{{ path('stuff_edit', {'id': stuff.id}) }}">edit</a>

    {{ include('stuff/_delete_form.html.twig') }}
{% endblock %}